language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script: cd client
script:
  - npm test
  - npm run build
deploy:

  skip_cleanup: true
  project: ./build/
on:
  branch: master
